from contextlib import contextmanager
from OpenGL.GL import *

@contextmanager
def bind(framebuffer):
	glBindFramebuffer(GL_FRAMEBUFFER, framebuffer)
	yield framebuffer
	glBindFramebuffer(GL_FRAMEBUFFER, 0)

STATUS = {
	GL_FRAMEBUFFER_COMPLETE: 'GL_FRAMEBUFFER_COMPLETE',
	GL_FRAMEBUFFER_UNDEFINED: 'GL_FRAMEBUFFER_UNDEFINED',
	GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT: 'GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT',
	GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT: 'GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT',
	GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER: 'GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER',
	GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER: 'GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER',
	GL_FRAMEBUFFER_UNSUPPORTED: 'GL_FRAMEBUFFER_UNSUPPORTED',
	

}